# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_calc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1618, 951)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("backhround-color:rgb(156, 156, 156)")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.base_params = QtWidgets.QWidget()
        self.base_params.setObjectName("base_params")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.base_params)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_fields = QtWidgets.QGridLayout()
        self.gridLayout_fields.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_fields.setHorizontalSpacing(15)
        self.gridLayout_fields.setVerticalSpacing(25)
        self.gridLayout_fields.setObjectName("gridLayout_fields")
        self.lineEdit_n_shoots = QtWidgets.QLineEdit(self.base_params)
        self.lineEdit_n_shoots.setObjectName("lineEdit_n_shoots")
        self.gridLayout_fields.addWidget(self.lineEdit_n_shoots, 2, 7, 1, 1)
        self.label_n_shoots = QtWidgets.QLabel(self.base_params)
        self.label_n_shoots.setObjectName("label_n_shoots")
        self.gridLayout_fields.addWidget(self.label_n_shoots, 2, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_fields.addItem(spacerItem, 0, 3, 1, 1)
        self.label_type = QtWidgets.QLabel(self.base_params)
        self.label_type.setObjectName("label_type")
        self.gridLayout_fields.addWidget(self.label_type, 1, 0, 1, 1)
        self.label_Ku = QtWidgets.QLabel(self.base_params)
        self.label_Ku.setObjectName("label_Ku")
        self.gridLayout_fields.addWidget(self.label_Ku, 1, 6, 1, 1)
        self.lineEdit_Ku = QtWidgets.QLineEdit(self.base_params)
        self.lineEdit_Ku.setObjectName("lineEdit_Ku")
        self.gridLayout_fields.addWidget(self.lineEdit_Ku, 1, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_fields.addItem(spacerItem1, 0, 8, 1, 1)
        self.label_q = QtWidgets.QLabel(self.base_params)
        self.label_q.setObjectName("label_q")
        self.gridLayout_fields.addWidget(self.label_q, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_fields.addItem(spacerItem2, 0, 5, 1, 1)
        self.lineEdit_q = QtWidgets.QLineEdit(self.base_params)
        self.lineEdit_q.setObjectName("lineEdit_q")
        self.gridLayout_fields.addWidget(self.lineEdit_q, 0, 1, 1, 1)
        self.comboBox_q = QtWidgets.QComboBox(self.base_params)
        self.comboBox_q.setObjectName("comboBox_q")
        self.gridLayout_fields.addWidget(self.comboBox_q, 0, 2, 1, 1)
        self.labe_n_cellsl = QtWidgets.QLabel(self.base_params)
        self.labe_n_cellsl.setObjectName("labe_n_cellsl")
        self.gridLayout_fields.addWidget(self.labe_n_cellsl, 0, 6, 1, 1)
        self.lineEdit_n_cells = QtWidgets.QLineEdit(self.base_params)
        self.lineEdit_n_cells.setObjectName("lineEdit_n_cells")
        self.gridLayout_fields.addWidget(self.lineEdit_n_cells, 0, 7, 1, 1)
        self.comboBox_type = QtWidgets.QComboBox(self.base_params)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_type.sizePolicy().hasHeightForWidth())
        self.comboBox_type.setSizePolicy(sizePolicy)
        self.comboBox_type.setObjectName("comboBox_type")
        self.gridLayout_fields.addWidget(self.comboBox_type, 1, 1, 1, 1)
        self.lineEdit_border_cam = QtWidgets.QLineEdit(self.base_params)
        self.lineEdit_border_cam.setObjectName("lineEdit_border_cam")
        self.gridLayout_fields.addWidget(self.lineEdit_border_cam, 2, 1, 1, 1)
        self.label_border_cam = QtWidgets.QLabel(self.base_params)
        self.label_border_cam.setObjectName("label_border_cam")
        self.gridLayout_fields.addWidget(self.label_border_cam, 2, 0, 1, 1)
        self.pushButton_border_cam = QtWidgets.QPushButton(self.base_params)
        self.pushButton_border_cam.setObjectName("pushButton_border_cam")
        self.gridLayout_fields.addWidget(self.pushButton_border_cam, 2, 2, 1, 1)
        self.label_points_geom_barell = QtWidgets.QLabel(self.base_params)
        self.label_points_geom_barell.setObjectName("label_points_geom_barell")
        self.gridLayout_fields.addWidget(self.label_points_geom_barell, 3, 0, 1, 1)
        self.lineEdit_points_geom_barell = QtWidgets.QLineEdit(self.base_params)
        self.lineEdit_points_geom_barell.setObjectName("lineEdit_points_geom_barell")
        self.gridLayout_fields.addWidget(self.lineEdit_points_geom_barell, 3, 1, 1, 1)
        self.pushButton_points_geom_barell = QtWidgets.QPushButton(self.base_params)
        self.pushButton_points_geom_barell.setObjectName("pushButton_points_geom_barell")
        self.gridLayout_fields.addWidget(self.pushButton_points_geom_barell, 3, 2, 1, 1)
        self.label_points_wall = QtWidgets.QLabel(self.base_params)
        self.label_points_wall.setObjectName("label_points_wall")
        self.gridLayout_fields.addWidget(self.label_points_wall, 4, 0, 1, 1)
        self.lineEdit_points_wall = QtWidgets.QLineEdit(self.base_params)
        self.lineEdit_points_wall.setObjectName("lineEdit_points_wall")
        self.gridLayout_fields.addWidget(self.lineEdit_points_wall, 4, 1, 1, 1)
        self.pushButton_points_wall = QtWidgets.QPushButton(self.base_params)
        self.pushButton_points_wall.setObjectName("pushButton_points_wall")
        self.gridLayout_fields.addWidget(self.pushButton_points_wall, 4, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.base_params)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_fields.addWidget(self.line_3, 0, 4, 5, 1)
        self.gridLayout_fields.setColumnStretch(0, 2)
        self.gridLayout_fields.setColumnStretch(1, 3)
        self.gridLayout_fields.setColumnStretch(2, 1)
        self.gridLayout_fields.setColumnStretch(3, 1)
        self.gridLayout_fields.setColumnStretch(4, 1)
        self.gridLayout_fields.setColumnStretch(5, 1)
        self.gridLayout_fields.setColumnStretch(6, 3)
        self.gridLayout_fields.setColumnStretch(7, 3)
        self.gridLayout_fields.setColumnStretch(8, 2)
        self.gridLayout_fields.setRowStretch(0, 2)
        self.verticalLayout.addLayout(self.gridLayout_fields)
        spacerItem3 = QtWidgets.QSpacerItem(20, 212, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_button = QtWidgets.QHBoxLayout()
        self.horizontalLayout_button.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_button.setObjectName("horizontalLayout_button")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_button.addItem(spacerItem4)
        self.pushButton_calc = QtWidgets.QPushButton(self.base_params)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_calc.sizePolicy().hasHeightForWidth())
        self.pushButton_calc.setSizePolicy(sizePolicy)
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.horizontalLayout_button.addWidget(self.pushButton_calc)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_button.addItem(spacerItem5)
        self.horizontalLayout_button.setStretch(0, 1)
        self.horizontalLayout_button.setStretch(1, 1)
        self.horizontalLayout_button.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_button)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 9)
        self.verticalLayout.setStretch(2, 12)
        self.tabWidget.addTab(self.base_params, "")
        self.params_powder = QtWidgets.QWidget()
        self.params_powder.setObjectName("params_powder")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.params_powder)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_work_body = QtWidgets.QHBoxLayout()
        self.horizontalLayout_work_body.setSpacing(6)
        self.horizontalLayout_work_body.setObjectName("horizontalLayout_work_body")
        self.gridLayout_base_powder = QtWidgets.QGridLayout()
        self.gridLayout_base_powder.setVerticalSpacing(15)
        self.gridLayout_base_powder.setObjectName("gridLayout_base_powder")
        self.label_omega = QtWidgets.QLabel(self.params_powder)
        self.label_omega.setObjectName("label_omega")
        self.gridLayout_base_powder.addWidget(self.label_omega, 1, 0, 1, 1)
        self.label_mark = QtWidgets.QLabel(self.params_powder)
        self.label_mark.setObjectName("label_mark")
        self.gridLayout_base_powder.addWidget(self.label_mark, 0, 0, 1, 1)
        self.lineEdit_omega = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_omega.setObjectName("lineEdit_omega")
        self.gridLayout_base_powder.addWidget(self.lineEdit_omega, 1, 1, 1, 1)
        self.comboBox_mark = QtWidgets.QComboBox(self.params_powder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_mark.sizePolicy().hasHeightForWidth())
        self.comboBox_mark.setSizePolicy(sizePolicy)
        self.comboBox_mark.setObjectName("comboBox_mark")
        self.gridLayout_base_powder.addWidget(self.comboBox_mark, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_base_powder.addItem(spacerItem6, 0, 2, 1, 1)
        self.lineEdit_pf = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_pf.setObjectName("lineEdit_pf")
        self.gridLayout_base_powder.addWidget(self.lineEdit_pf, 2, 1, 1, 1)
        self.label_pf = QtWidgets.QLabel(self.params_powder)
        self.label_pf.setObjectName("label_pf")
        self.gridLayout_base_powder.addWidget(self.label_pf, 2, 0, 1, 1)
        self.comboBox_omega = QtWidgets.QComboBox(self.params_powder)
        self.comboBox_omega.setObjectName("comboBox_omega")
        self.gridLayout_base_powder.addWidget(self.comboBox_omega, 1, 2, 1, 1)
        self.comboBox_pf = QtWidgets.QComboBox(self.params_powder)
        self.comboBox_pf.setObjectName("comboBox_pf")
        self.gridLayout_base_powder.addWidget(self.comboBox_pf, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.params_powder)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_base_powder.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_base_powder.setColumnStretch(0, 4)
        self.gridLayout_base_powder.setColumnStretch(1, 4)
        self.gridLayout_base_powder.setColumnStretch(2, 1)
        self.gridLayout_base_powder.setRowStretch(0, 2)
        self.gridLayout_base_powder.setRowStretch(1, 1)
        self.gridLayout_base_powder.setRowStretch(2, 1)
        self.gridLayout_base_powder.setRowStretch(3, 16)
        self.horizontalLayout_work_body.addLayout(self.gridLayout_base_powder)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_work_body.addItem(spacerItem7)
        self.line_2 = QtWidgets.QFrame(self.params_powder)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_work_body.addWidget(self.line_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_work_body.addItem(spacerItem8)
        self.verticalLayout_charact_powder = QtWidgets.QVBoxLayout()
        self.verticalLayout_charact_powder.setSpacing(15)
        self.verticalLayout_charact_powder.setObjectName("verticalLayout_charact_powder")
        self.label_params_powder = QtWidgets.QLabel(self.params_powder)
        self.label_params_powder.setObjectName("label_params_powder")
        self.verticalLayout_charact_powder.addWidget(self.label_params_powder)
        self.line_params_powder = QtWidgets.QFrame(self.params_powder)
        self.line_params_powder.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_params_powder.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_params_powder.setObjectName("line_params_powder")
        self.verticalLayout_charact_powder.addWidget(self.line_params_powder)
        self.gridLayout_charact_wo_coef = QtWidgets.QGridLayout()
        self.gridLayout_charact_wo_coef.setVerticalSpacing(15)
        self.gridLayout_charact_wo_coef.setObjectName("gridLayout_charact_wo_coef")
        self.label_covolum = QtWidgets.QLabel(self.params_powder)
        self.label_covolum.setObjectName("label_covolum")
        self.gridLayout_charact_wo_coef.addWidget(self.label_covolum, 4, 0, 1, 1)
        self.lineEdit_covolum = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_covolum.setObjectName("lineEdit_covolum")
        self.gridLayout_charact_wo_coef.addWidget(self.lineEdit_covolum, 4, 1, 1, 1)
        self.label_zk = QtWidgets.QLabel(self.params_powder)
        self.label_zk.setObjectName("label_zk")
        self.gridLayout_charact_wo_coef.addWidget(self.label_zk, 5, 0, 1, 1)
        self.lineEdit_zk = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_zk.setObjectName("lineEdit_zk")
        self.gridLayout_charact_wo_coef.addWidget(self.lineEdit_zk, 5, 1, 1, 1)
        self.label_nu = QtWidgets.QLabel(self.params_powder)
        self.label_nu.setObjectName("label_nu")
        self.gridLayout_charact_wo_coef.addWidget(self.label_nu, 6, 0, 1, 1)
        self.lineEdit_nu = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_nu.setObjectName("lineEdit_nu")
        self.gridLayout_charact_wo_coef.addWidget(self.lineEdit_nu, 6, 1, 1, 1)
        self.lineEdit_rho = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_rho.setObjectName("lineEdit_rho")
        self.gridLayout_charact_wo_coef.addWidget(self.lineEdit_rho, 2, 1, 1, 1)
        self.label_rho = QtWidgets.QLabel(self.params_powder)
        self.label_rho.setObjectName("label_rho")
        self.gridLayout_charact_wo_coef.addWidget(self.label_rho, 2, 0, 1, 1)
        self.lineEdit_gamma = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_gamma.setObjectName("lineEdit_gamma")
        self.gridLayout_charact_wo_coef.addWidget(self.lineEdit_gamma, 3, 1, 1, 1)
        self.label_gamma = QtWidgets.QLabel(self.params_powder)
        self.label_gamma.setObjectName("label_gamma")
        self.gridLayout_charact_wo_coef.addWidget(self.label_gamma, 3, 0, 1, 1)
        self.label_Ik = QtWidgets.QLabel(self.params_powder)
        self.label_Ik.setObjectName("label_Ik")
        self.gridLayout_charact_wo_coef.addWidget(self.label_Ik, 0, 0, 1, 1)
        self.lineEdit_Ik = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_Ik.setObjectName("lineEdit_Ik")
        self.gridLayout_charact_wo_coef.addWidget(self.lineEdit_Ik, 0, 1, 1, 1)
        self.label_f = QtWidgets.QLabel(self.params_powder)
        self.label_f.setObjectName("label_f")
        self.gridLayout_charact_wo_coef.addWidget(self.label_f, 1, 0, 1, 1)
        self.lineEdit_f = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_f.setObjectName("lineEdit_f")
        self.gridLayout_charact_wo_coef.addWidget(self.lineEdit_f, 1, 1, 1, 1)
        self.gridLayout_charact_wo_coef.setColumnStretch(0, 3)
        self.verticalLayout_charact_powder.addLayout(self.gridLayout_charact_wo_coef)
        self.verticalLayout_coef = QtWidgets.QVBoxLayout()
        self.verticalLayout_coef.setSpacing(15)
        self.verticalLayout_coef.setObjectName("verticalLayout_coef")
        self.label_coeff_form_powder = QtWidgets.QLabel(self.params_powder)
        self.label_coeff_form_powder.setObjectName("label_coeff_form_powder")
        self.verticalLayout_coef.addWidget(self.label_coeff_form_powder)
        self.gridLayout_coef = QtWidgets.QGridLayout()
        self.gridLayout_coef.setVerticalSpacing(15)
        self.gridLayout_coef.setObjectName("gridLayout_coef")
        self.lineEdit_lambda1_1 = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_lambda1_1.setObjectName("lineEdit_lambda1_1")
        self.gridLayout_coef.addWidget(self.lineEdit_lambda1_1, 0, 1, 1, 1)
        self.label_kappa_1 = QtWidgets.QLabel(self.params_powder)
        self.label_kappa_1.setObjectName("label_kappa_1")
        self.gridLayout_coef.addWidget(self.label_kappa_1, 1, 0, 1, 1)
        self.label_lambda_1 = QtWidgets.QLabel(self.params_powder)
        self.label_lambda_1.setObjectName("label_lambda_1")
        self.gridLayout_coef.addWidget(self.label_lambda_1, 0, 0, 1, 1)
        self.lineEdit_kappa_1 = QtWidgets.QLineEdit(self.params_powder)
        self.lineEdit_kappa_1.setObjectName("lineEdit_kappa_1")
        self.gridLayout_coef.addWidget(self.lineEdit_kappa_1, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_coef.addItem(spacerItem9, 0, 2, 1, 1)
        self.gridLayout_coef.setColumnStretch(0, 1)
        self.gridLayout_coef.setColumnStretch(1, 2)
        self.gridLayout_coef.setColumnStretch(2, 10)
        self.verticalLayout_coef.addLayout(self.gridLayout_coef)
        self.verticalLayout_charact_powder.addLayout(self.verticalLayout_coef)
        self.horizontalLayout_work_body.addLayout(self.verticalLayout_charact_powder)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_work_body.addItem(spacerItem10)
        self.horizontalLayout_work_body.setStretch(0, 7)
        self.horizontalLayout_work_body.setStretch(4, 7)
        self.horizontalLayout_work_body.setStretch(5, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_work_body)
        spacerItem11 = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.tabWidget.addTab(self.params_powder, "")
        self.params_gas = QtWidgets.QWidget()
        self.params_gas.setObjectName("params_gas")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.params_gas)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_params_gas = QtWidgets.QHBoxLayout()
        self.horizontalLayout_params_gas.setObjectName("horizontalLayout_params_gas")
        self.gridLayout_base_gas = QtWidgets.QGridLayout()
        self.gridLayout_base_gas.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_base_gas.setHorizontalSpacing(15)
        self.gridLayout_base_gas.setVerticalSpacing(33)
        self.gridLayout_base_gas.setObjectName("gridLayout_base_gas")
        self.label_kind_gas = QtWidgets.QLabel(self.params_gas)
        self.label_kind_gas.setObjectName("label_kind_gas")
        self.gridLayout_base_gas.addWidget(self.label_kind_gas, 0, 0, 1, 1)
        self.comboBox_gas = QtWidgets.QComboBox(self.params_gas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_gas.sizePolicy().hasHeightForWidth())
        self.comboBox_gas.setSizePolicy(sizePolicy)
        self.comboBox_gas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_gas.setObjectName("comboBox_gas")
        self.gridLayout_base_gas.addWidget(self.comboBox_gas, 0, 1, 1, 1)
        self.label_pressure_gas = QtWidgets.QLabel(self.params_gas)
        self.label_pressure_gas.setObjectName("label_pressure_gas")
        self.gridLayout_base_gas.addWidget(self.label_pressure_gas, 1, 0, 1, 1)
        self.lineEdit_pressure_gas = QtWidgets.QLineEdit(self.params_gas)
        self.lineEdit_pressure_gas.setObjectName("lineEdit_pressure_gas")
        self.gridLayout_base_gas.addWidget(self.lineEdit_pressure_gas, 1, 1, 1, 1)
        self.comboBox_pressure_gas = QtWidgets.QComboBox(self.params_gas)
        self.comboBox_pressure_gas.setObjectName("comboBox_pressure_gas")
        self.gridLayout_base_gas.addWidget(self.comboBox_pressure_gas, 1, 2, 1, 1)
        self.label_temp_gas = QtWidgets.QLabel(self.params_gas)
        self.label_temp_gas.setObjectName("label_temp_gas")
        self.gridLayout_base_gas.addWidget(self.label_temp_gas, 2, 0, 1, 1)
        self.lineEdit_temp_gas = QtWidgets.QLineEdit(self.params_gas)
        self.lineEdit_temp_gas.setObjectName("lineEdit_temp_gas")
        self.gridLayout_base_gas.addWidget(self.lineEdit_temp_gas, 2, 1, 1, 1)
        self.comboBox_temp_gas = QtWidgets.QComboBox(self.params_gas)
        self.comboBox_temp_gas.setObjectName("comboBox_temp_gas")
        self.gridLayout_base_gas.addWidget(self.comboBox_temp_gas, 2, 2, 1, 1)
        self.horizontalLayout_params_gas.addLayout(self.gridLayout_base_gas)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_params_gas.addItem(spacerItem12)
        self.verticalLayout_char_gas = QtWidgets.QVBoxLayout()
        self.verticalLayout_char_gas.setObjectName("verticalLayout_char_gas")
        self.label_charact_gas = QtWidgets.QLabel(self.params_gas)
        self.label_charact_gas.setObjectName("label_charact_gas")
        self.verticalLayout_char_gas.addWidget(self.label_charact_gas)
        self.line_gas = QtWidgets.QFrame(self.params_gas)
        self.line_gas.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gas.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gas.setObjectName("line_gas")
        self.verticalLayout_char_gas.addWidget(self.line_gas)
        self.gridLayout_char_gas = QtWidgets.QGridLayout()
        self.gridLayout_char_gas.setSpacing(15)
        self.gridLayout_char_gas.setObjectName("gridLayout_char_gas")
        self.label_R_gas = QtWidgets.QLabel(self.params_gas)
        self.label_R_gas.setObjectName("label_R_gas")
        self.gridLayout_char_gas.addWidget(self.label_R_gas, 0, 0, 1, 1)
        self.lineEdit_R_gas = QtWidgets.QLineEdit(self.params_gas)
        self.lineEdit_R_gas.setObjectName("lineEdit_R_gas")
        self.gridLayout_char_gas.addWidget(self.lineEdit_R_gas, 0, 1, 1, 1)
        self.label_gamma_gas = QtWidgets.QLabel(self.params_gas)
        self.label_gamma_gas.setObjectName("label_gamma_gas")
        self.gridLayout_char_gas.addWidget(self.label_gamma_gas, 1, 0, 1, 1)
        self.lineEdit_gamma_gas = QtWidgets.QLineEdit(self.params_gas)
        self.lineEdit_gamma_gas.setObjectName("lineEdit_gamma_gas")
        self.gridLayout_char_gas.addWidget(self.lineEdit_gamma_gas, 1, 1, 1, 1)
        self.label_covolum_gas = QtWidgets.QLabel(self.params_gas)
        self.label_covolum_gas.setObjectName("label_covolum_gas")
        self.gridLayout_char_gas.addWidget(self.label_covolum_gas, 2, 0, 1, 1)
        self.lineEdit_covolum_gas = QtWidgets.QLineEdit(self.params_gas)
        self.lineEdit_covolum_gas.setObjectName("lineEdit_covolum_gas")
        self.gridLayout_char_gas.addWidget(self.lineEdit_covolum_gas, 2, 1, 1, 1)
        self.verticalLayout_char_gas.addLayout(self.gridLayout_char_gas)
        self.horizontalLayout_params_gas.addLayout(self.verticalLayout_char_gas)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_params_gas.addItem(spacerItem13)
        self.horizontalLayout_params_gas.setStretch(0, 4)
        self.horizontalLayout_params_gas.setStretch(1, 1)
        self.horizontalLayout_params_gas.setStretch(2, 4)
        self.horizontalLayout_params_gas.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_params_gas)
        spacerItem14 = QtWidgets.QSpacerItem(20, 248, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem14)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 4)
        self.tabWidget.addTab(self.params_gas, "")
        self.params_materials = QtWidgets.QWidget()
        self.params_materials.setObjectName("params_materials")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.params_materials)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem15)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_materials = QtWidgets.QLabel(self.params_materials)
        self.label_materials.setObjectName("label_materials")
        self.horizontalLayout_2.addWidget(self.label_materials)
        self.comboBox_materials = QtWidgets.QComboBox(self.params_materials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_materials.sizePolicy().hasHeightForWidth())
        self.comboBox_materials.setSizePolicy(sizePolicy)
        self.comboBox_materials.setCurrentText("")
        self.comboBox_materials.setObjectName("comboBox_materials")
        self.horizontalLayout_2.addWidget(self.comboBox_materials)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem16)
        self.verticalLayout_5.setStretch(0, 3)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_5.setStretch(2, 3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_char_materials = QtWidgets.QLabel(self.params_materials)
        self.label_char_materials.setObjectName("label_char_materials")
        self.verticalLayout_2.addWidget(self.label_char_materials)
        self.line_materials = QtWidgets.QFrame(self.params_materials)
        self.line_materials.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_materials.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_materials.setObjectName("line_materials")
        self.verticalLayout_2.addWidget(self.line_materials)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_cp_materials = QtWidgets.QLabel(self.params_materials)
        self.label_cp_materials.setObjectName("label_cp_materials")
        self.gridLayout_3.addWidget(self.label_cp_materials, 3, 0, 1, 1)
        self.lineEdit_cp_materials = QtWidgets.QLineEdit(self.params_materials)
        self.lineEdit_cp_materials.setObjectName("lineEdit_cp_materials")
        self.gridLayout_3.addWidget(self.lineEdit_cp_materials, 3, 1, 1, 1)
        self.lineEdit_lambda_materials = QtWidgets.QLineEdit(self.params_materials)
        self.lineEdit_lambda_materials.setObjectName("lineEdit_lambda_materials")
        self.gridLayout_3.addWidget(self.lineEdit_lambda_materials, 2, 1, 1, 1)
        self.label_2_lambda_materials = QtWidgets.QLabel(self.params_materials)
        self.label_2_lambda_materials.setObjectName("label_2_lambda_materials")
        self.gridLayout_3.addWidget(self.label_2_lambda_materials, 2, 0, 1, 1)
        self.comboBox_rho_materials = QtWidgets.QComboBox(self.params_materials)
        self.comboBox_rho_materials.setObjectName("comboBox_rho_materials")
        self.gridLayout_3.addWidget(self.comboBox_rho_materials, 0, 2, 1, 1)
        self.label_rho_materials = QtWidgets.QLabel(self.params_materials)
        self.label_rho_materials.setObjectName("label_rho_materials")
        self.gridLayout_3.addWidget(self.label_rho_materials, 0, 0, 1, 1)
        self.lineEdit_rho_materials = QtWidgets.QLineEdit(self.params_materials)
        self.lineEdit_rho_materials.setObjectName("lineEdit_rho_materials")
        self.gridLayout_3.addWidget(self.lineEdit_rho_materials, 0, 1, 1, 1)
        self.label_sigma_v = QtWidgets.QLabel(self.params_materials)
        self.label_sigma_v.setObjectName("label_sigma_v")
        self.gridLayout_3.addWidget(self.label_sigma_v, 1, 0, 1, 1)
        self.lineEdit_sigma_v = QtWidgets.QLineEdit(self.params_materials)
        self.lineEdit_sigma_v.setObjectName("lineEdit_sigma_v")
        self.gridLayout_3.addWidget(self.lineEdit_sigma_v, 1, 1, 1, 1)
        self.comboBox_sigma_v = QtWidgets.QComboBox(self.params_materials)
        self.comboBox_sigma_v.setObjectName("comboBox_sigma_v")
        self.gridLayout_3.addWidget(self.comboBox_sigma_v, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 6)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem19 = QtWidgets.QSpacerItem(20, 228, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem19)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 3)
        self.tabWidget.addTab(self.params_materials, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 5)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1618, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.action_new_file = QtWidgets.QAction(MainWindow)
        self.action_new_file.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Vitaliy/.designer/icon/new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_new_file.setIcon(icon)
        self.action_new_file.setObjectName("action_new_file")
        self.action_geometry = QtWidgets.QAction(MainWindow)
        self.action_geometry.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Vitaliy/.designer/icon/geometry.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_geometry.setIcon(icon1)
        self.action_geometry.setObjectName("action_geometry")
        self.menu.addAction(self.action_new_file)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.action_geometry)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_n_shoots.setText(_translate("MainWindow", "Количество выстрелов"))
        self.label_type.setText(_translate("MainWindow", "Тип рабочего тела"))
        self.label_Ku.setText(_translate("MainWindow", "Число Куранта"))
        self.label_q.setText(_translate("MainWindow", "Масса снаряда"))
        self.labe_n_cellsl.setText(_translate("MainWindow", "Количество узлов разностной сетки"))
        self.label_border_cam.setText(_translate("MainWindow", "<html><head/><body><p>Выберите правую границу </p><p>камеры сгорания</p></body></html>"))
        self.pushButton_border_cam.setText(_translate("MainWindow", "Выбрать"))
        self.label_points_geom_barell.setText(_translate("MainWindow", "Выберите точки, через\n"
"которые проходит внутренняя\n"
"стенка канала ствола"))
        self.pushButton_points_geom_barell.setText(_translate("MainWindow", "Выбрать"))
        self.label_points_wall.setText(_translate("MainWindow", "Выберите точки, которые \n"
"ограничивают периметр \n"
"стенки"))
        self.pushButton_points_wall.setText(_translate("MainWindow", "Выбрать"))
        self.pushButton_calc.setText(_translate("MainWindow", "Запустить расчёт"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.base_params), _translate("MainWindow", "Основные параметры"))
        self.label_omega.setText(_translate("MainWindow", "Масса навески пороха"))
        self.label_mark.setText(_translate("MainWindow", "Марка пороха"))
        self.label_pf.setText(_translate("MainWindow", "Давление форсирования"))
        self.label_params_powder.setText(_translate("MainWindow", "Характеристики пороха"))
        self.label_covolum.setText(_translate("MainWindow", "<html><head/><body><p>Коволюм единицы массы пороховых газов, дм<span style=\" vertical-align:super;\">3</span>/кг</p></body></html>"))
        self.label_zk.setText(_translate("MainWindow", "Относительная толщина конца горения пороха"))
        self.label_nu.setText(_translate("MainWindow", "Показатель в законе горения"))
        self.label_rho.setText(_translate("MainWindow", "<html><head/><body><p>Плотность пороха, кг/дм<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.label_gamma.setText(_translate("MainWindow", "Показатель адиабаты пороховых газов"))
        self.label_Ik.setText(_translate("MainWindow", "Импульс конца горения пороха, МПа ∙ с"))
        self.label_f.setText(_translate("MainWindow", "Сила пороха, МДж/кг"))
        self.label_coeff_form_powder.setText(_translate("MainWindow", "Коэффициенты характеризующие форму порохового заряда"))
        self.label_kappa_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Calibri,sans-serif\'; font-size:11pt;\">κ</span></p></body></html>"))
        self.label_lambda_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Calibri,sans-serif\'; font-size:11pt;\">λ</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.params_powder), _translate("MainWindow", "Параметры пороха"))
        self.label_kind_gas.setText(_translate("MainWindow", "Газ"))
        self.label_pressure_gas.setText(_translate("MainWindow", "Давление газа в камере"))
        self.label_temp_gas.setText(_translate("MainWindow", "Температура газа в камере"))
        self.label_charact_gas.setText(_translate("MainWindow", "Характеристики газа"))
        self.label_R_gas.setText(_translate("MainWindow", "Газовая постоянная Дж/(кг ∙ К)"))
        self.label_gamma_gas.setText(_translate("MainWindow", "Показатель адиабаты"))
        self.label_covolum_gas.setText(_translate("MainWindow", "Коволюм"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.params_gas), _translate("MainWindow", "Параметры газа"))
        self.label_materials.setText(_translate("MainWindow", "Материал ствола"))
        self.label_char_materials.setText(_translate("MainWindow", "Характеристики матеирала"))
        self.label_cp_materials.setText(_translate("MainWindow", "<html><head/><body><p>Удельная теплоемкость при постоянном давлении, Дж/(кг ∙ ⁰С)</p></body></html>"))
        self.label_2_lambda_materials.setText(_translate("MainWindow", "<html><head/><body><p>Коэффициент теплопроводности, Вт/(м ∙ ⁰С)</p></body></html>"))
        self.label_rho_materials.setText(_translate("MainWindow", "Плотность"))
        self.label_sigma_v.setText(_translate("MainWindow", "Предел упругости"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.params_materials), _translate("MainWindow", "Параметры материала ствола"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.action_new_file.setText(_translate("MainWindow", "Новый расчет"))
        self.action_geometry.setText(_translate("MainWindow", "action_geometry"))
        self.action_geometry.setShortcut(_translate("MainWindow", "Ctrl+G"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
